/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CronForm: typeof import('./src/components/GenCron/CronForm/index.vue')['default']
    CronModal: typeof import('./src/components/GenCron/CronModal/index.vue')['default']
    DayForm: typeof import('./src/components/GenCron/CronForm/component/day-form.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    GiPageLayout: typeof import('./src/components/GiPageLayout/index.vue')['default']
    HourForm: typeof import('./src/components/GenCron/CronForm/component/hour-form.vue')['default']
    MenuSelectTable: typeof import('./src/components/tree/src/menu-select-table.vue')['default']
    MinuteForm: typeof import('./src/components/GenCron/CronForm/component/minute-form.vue')['default']
    MonthForm: typeof import('./src/components/GenCron/CronForm/component/month-form.vue')['default']
    RichText: typeof import('./src/components/richText/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondForm: typeof import('./src/components/GenCron/CronForm/component/second-form.vue')['default']
    Src: typeof import('./src/components/dict/src/index.vue')['default']
    TreeSelectPanel: typeof import('./src/components/tree/src/tree-select-panel.vue')['default']
    WeekForm: typeof import('./src/components/GenCron/CronForm/component/week-form.vue')['default']
    YearForm: typeof import('./src/components/GenCron/CronForm/component/year-form.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
